     catch (Exception ex)
     {
         var contextMessage = $"Unexpected exception in UserInformation. UserId: {userId}";
         _log.Error(ex, contextMessage);
         throw; // if logging is enough and rethrow keeps the trace
     }

Either log this exception and handle it, or rethrow it with some contextual information. (csharpsquid:S2139 )
